### ISSUE TITLE
fix bug "Unable to add window -- token android.os.BinderProxy is not valid"

### ISSUE THREAD

**Issue by abertschi** [abertschi/ad-free#44]
related to the file chooser view for selection of audio tracks.
```
Android version: 28
Device: samsung SM-G960U
App version: 33
Time: 2019-11-25-22:09:20
Root cause:
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@99507bb is not valid; is your activity running?
at android.view.ViewRootImpl.setView(ViewRootImpl.java:1056)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:381)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
at android.app.Dialog.show(Dialog.java:470)
at com.github.angads25.filepicker.view.FilePickerDialog.show(FilePickerDialog.java:417)
at ch.abertschi.adfree.plugin.localmusic.LocalMusicView.showFolderSelectionDialog(LocalMusicView.kt:98)
at ch.abertschi.adfree.plugin.localmusic.LocalMusicPlugin.chooseDirectory(LocalMusicPlugin.kt:141)
at ch.abertschi.adfree.plugin.localmusic.LocalMusicView$onCreate$4.onClick(LocalMusicView.kt:71)
at android.view.View.performClick(View.java:7333)
at android.widget.TextView.performClick(TextView.java:14160)
at android.view.View.performClickInternal(View.java:7299)
at android.view.View.access$3200(View.java:846)
at android.view.View$PerformClick.run(View.java:27773)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:6986)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by abertschi** [comment]
fixed in version #52

**Comment by abertschi** [comment]
Still a bug in v2.2

**Comment by abertschi** [comment]
#84
