### ISSUE TITLE
Crashed when on screen with local music settings

### ISSUE THREAD

**Issue by dkocich** [abertschi/ad-free#78]
Android version: 30
Device: OnePlus IN2023
App version: 36
Time: 2021-05-30-18:47:18
Root cause: 
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@8e23fa7 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1159)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:421)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:110)
	at android.app.Dialog.show(Dialog.java:340)
	at ch.abertschi.adfree.plugin.localmusic.LocalMusicView.showFolderSelectionDialog(LocalMusicView.kt:123)
	at ch.abertschi.adfree.plugin.localmusic.LocalMusicPlugin.onChooseDirectory(LocalMusicPlugin.kt:161)
	at ch.abertschi.adfree.plugin.localmusic.LocalMusicView$setupUi$12.onClick(LocalMusicView.kt:92)
	at android.view.View.performClick(View.java:7520)
	at android.view.View.performClickInternal(View.java:7489)
	at android.view.View.access$3600(View.java:826)
	at android.view.View$PerformClick.run(View.java:28555)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by abertschi** [comment]
#84
